# Generated by Django 4.2.3 on 2023-09-21 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_productimages_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='specificatoin',
            new_name='specification',
        ),
    ]
