# Generated by Django 4.2.3 on 2023-12-26 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_rename_contactus_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
