# Generated by Django 4.2.3 on 2023-12-27 13:07

from django.db import migrations, models
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_cartorder_order_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='replies',
        ),
        migrations.AddField(
            model_name='thread',
            name='image',
            field=models.ImageField(default='thread.png', upload_to='user_directory_path'),
        ),
        migrations.AddField(
            model_name='thread',
            name='tid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh12345', length=10, max_length=20, prefix='thr', unique=True),
        ),
    ]
