# Generated by Django 4.2.3 on 2023-12-26 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauthentication', '0003_contactus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name': 'Contact Us', 'verbose_name_plural': 'Contact Us'},
        ),
    ]
