# Generated by Django 4.2.3 on 2023-12-26 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauthentication', '0004_alter_contactus_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='mobile',
            new_name='phone',
        ),
    ]
