# Generated by Django 4.2.3 on 2023-12-29 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauthentication', '0005_rename_mobile_contactus_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='experience',
            field=models.CharField(default='Satisfied', max_length=100),
        ),
    ]
